

name: ExtDN Integration Tests
on: [push]

jobs:
  integration-tests:
    name: Magento 2 Integration Tests
    runs-on: ubuntu-latest
    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: root
        ports:
          - 3306:3306
        options: --tmpfs /tmp:rw --tmpfs /var/lib/mysql:rw --health-cmd="mysqladmin ping"
    steps:
      - uses: actions/checkout@v2
      - uses: ./magento-e2e-tests/8.1
        env:
          MAGENTO_VERSION: '2.4.4'
          COMPOSER_VERSION: '2'